plugins { id 'com.android.application' }

android {
    namespace 'com.inthesky.radar.phone'
    compileSdk 34

    defaultConfig {
        applicationId 'com.inthesky.radar.phone'
        minSdk 28
        targetSdk 34
        versionCode 18
        versionName '0.6.6'
    }
}


dependencies {
    implementation 'com.rokid.cxr:client-l:1.1.1'
}
