plugins { id 'com.android.application' }

android {
    namespace 'com.inthesky.radar.phone'
    compileSdk 34

    defaultConfig {
        applicationId 'com.inthesky.radar.phone'
        minSdk 28
        targetSdk 34
        versionCode 7
        versionName '0.4.3'
    }
}


dependencies {
    implementation 'com.rokid.cxr:client-m:1.0.8'
}
