plugins { id 'com.android.application' }

android {
    namespace 'com.inthesky.radar.glasses'
    compileSdk 34

    defaultConfig {
        applicationId 'com.inthesky.radar.glasses'
        minSdk 28
        targetSdk 34
        versionCode 6
        versionName '0.4.2'
    }
}


dependencies {
    implementation 'com.rokid.cxr:cxr-service-bridge:1.0-SNAPSHOT'
}
