plugins { id 'com.android.application' }

android {
    namespace 'com.inthesky.radar.glasses'
    compileSdk 34

    defaultConfig {
        applicationId 'com.inthesky.radar.glasses'
        minSdk 28
        targetSdk 34
        versionCode 8
        versionName '0.4.4'
    }
}


dependencies {
    implementation 'com.rokid.cxr:cxr-service-bridge:1.0-20260728.074302-110'
}
